### PR TITLE
Fix WSOD on subsites when creating subsite page in front end theme

### LINKED ISSUE #154: Create a subsite page using front end theme causes WSOD
Eg. Using Mercury Editor which uses the front end theme for layout paragraphs.

> TypeError: PNX\NestedSet\NodeKey::__construct(): Argument 1 ($id) must be of type string|int, null given, called in /Users/Andy/Sites/bhcclocalgov/docroot/modules/contrib/entity_hierarchy/src/Storage/NestedSetNodeKeyFactory.php on line 29 in PNX\NestedSet\NodeKey->__construct() (line 21 of /Users/Andy/Sites/bhcclocalgov/vendor/previousnext/nested-set/src/NodeKey.php).

Traced this to the get subsite method

> Drupal\entity_hierarchy\Storage\NestedSetNodeKeyFactory->fromEntity(Object) (Line: 118)
> Drupal\localgov_subsites\Plugin\Block\SubsitesAbstractBlockBase->getRootId(Object) (Line: 80)
> Drupal\localgov_subsites\Plugin\Block\SubsitesAbstractBlockBase->getSubsite() (Line: 155)
> Drupal\localgov_subsites\Plugin\Block\SubsitesNavigationBlock->blockAccess(Object) (Line: 127)

The subsite is trying to get the rootID for the navigation block, but since no parent is yet set as it's being created, it can't.

We should short circuit it if we are trying to create a new node.

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #154

## What does this change?

Checks the entity ID is numeric (is not null) when trying to find subsite.
Adds a test to verify status code is 200 (500 without this fix).

## How to test

1. Set appearance to use the front end theme as the admin theme, or use an editor like [mercury editor](https://dgo.to/mercury_editor).
2. Create a new Subsite page at /node/add/localgov_subsite_page
3. Should be able to add a page without errors.

## How can we measure success?

Creating a subsite page no longer crashes.

## Have we considered potential risks?

Need to check side effects on the blocks not finding their subsite.
I noticed that using `is_int` does fail as `$entity->id()` brings back a string, might fail strict types.

## Images

N/A - Using front end theme is optional for sites that want to do so.

## Accessibility

N/A

### CODE REVIEW

File: src/Plugin/Block/SubsitesHierarchyTrait.php [hunk 1]
```diff
@@ -114,6 +114,7 @@ protected function getRootId(EntityInterface $entity): ?int {
         'localgov_subsites_overview',
         'localgov_subsites_page',
       ], TRUE)
+      && is_numeric($entity->id())
```
Comment (millnut) [inline src/Plugin/Block/SubsitesHierarchyTrait.php]: Would changing to is_null work if it could be a string?

```suggestion
      && !is_null($entity->id())
```

Comment (andybroomfield) [reply src/Plugin/Block/SubsitesHierarchyTrait.php]: We can try that, if that would be more correct.

**Review by stephen-cox — APPROVED** [review]
I haven't checked this fixes creating a node through the a frontend editor, but the change fixes what the test checks and it doesn't look to have any other side-effects.

**Review by ekes — APPROVED** [review]
