### PR TITLE
Fix PHP error on subsite page when overview is unpublished

### LINKED ISSUE #118: Subsite preview links are broken if the subsite overview is unpublished (causing WSOD)
When a comms officer was trying to share a preview link to a subsite page that wasn't public yet, they encountered a problem for those clicking the link, as they where getting the WSOD technicalk difficulties message.

On closer inspection, the following PHP error was being triggered.
> UnexpectedValueException: Object not found in SplObjectStorage->offsetGet() (line 59 of /mnt/www/html/brightonhovemain/docroot/modules/contrib/localgov_subsites/src/Plugin/Block/SubsitesNavigationBlock.php).

This occurs as the subsitenavigationblock is building all menu links using 
`$entities = $mapper->loadAndAccessCheckEntitysForTreeNodes('node', $tree, $cache);` 
and then tries to get the subsite id using 
`$subsite_id = $entities[$ancestors[0]]->id();`.
But since the overview is unpublished, this will fail as its blank.
Wrapping an empty check around this and setting subsite_id ?? NULL if blank does seem to resolve this issue, though it's not an ideal fix.

Steps to replicate
1. Create a subsite overview, but don't publish
2. Create a subsite page that uses the unpublished overview as the parent
3. Generate a preview line for the subsite page
4. Try to use the preview link in a private browsing window.

Expected result
Subsite page is shown, albeit with only the page in the navigation menu

Actual resule
WSOD, PHP error or technical difficulities message depending on setup.

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #118

Set the $subsite_id and $overview_entity to NULL if the overview is unpublished and the user doesn't have access to it. (It's not found in loadAndAccessCheckEntitysForTreeNodes).

This also required a change in the subsite navigation twig to check that the link has a url before attempting to output it, a simmilar change will be needed on any theme that has implemented the template.

Note: The test fails here due to the way the blocks cache.

### CODE REVIEW

**Comment by andybroomfield** [comment]
So an alternative is to use `loadEntitiesForTreeNodesWithoutAccessChecks` just to look for the parent subsite ID, which is needed to add a cache context.
I assume that as the navigation block, there is no real risk in leaking the subsite entity to the template if the overview entity is fetched for cache purposes?

**Comment by stephen-cox** [comment]
@andybroomfield It's definitely a caching issue, but I have only managed to solve it by adding a `drupal_flush_all_caches();` before getting the subsite_page1 contents.

I think this is fine so will push the change.

**Review by stephen-cox — APPROVED** [review]
Now the test is passing it's looking good to me

File: tests/src/Functional/SubsiteBlocksTest.php [hunk 1]
```diff
@@ -233,6 +233,17 @@ public function testSubsiteNavigationBlock() {
     $this->assertSession()->responseNotContains('block-localgov-subsite-navigation');
     $this->drupalGet($subsite_page1->toUrl()->toString());
     $this->assertSession()->responseNotContains('block-localgov-subsite-navigation');
+
+    // Test the navigation is still avalible with an unpublished overview node.
+    $subsite_overview->set('localgov_subsites_hide_menu', ['value' => 0]);
+    $subsite_overview->set('status', NodeInterface::NOT_PUBLISHED);
+    $subsite_overview->save();
+    drupal_flush_all_caches();
```
Comment (andybroomfield) [inline tests/src/Functional/SubsiteBlocksTest.php:241]: So my question is, is it ok to add a `drupal_flush_all_cache` here because what caused the cache break is the cache tags arn't being expired since its not saving the form?

Comment (stephen-cox) [reply tests/src/Functional/SubsiteBlocksTest.php:241]: I tried clearing the node cache for the nodes involved and the render cache and that didn't fix things, so I think it's fine.
