### PR TITLE
fix: phpstan issues

### LINKED ISSUE #127: Drupal 10, PHP 8.2 and PHPStan issues
The work on https://github.com/localgovdrupal/localgov_project/pull/131 has highlighted some PHP 8.2 and PHPStan issues which need fixing.

```
 ------ ---------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_subsites/src/Plugin/Block/SubsitesAbstractBlockBase.php                                      
 ------ ---------------------------------------------------------------------------------------------------------------------- 
  56     Access to an undefined property Drupal\localgov_subsites\Plugin\Block\SubsitesAbstractBlockBase::$entityTypeManager.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                  
  74     Access to an undefined property Drupal\localgov_subsites\Plugin\Block\SubsitesAbstractBlockBase::$entityTypeManager.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                  
 ------ ---------------------------------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_subsites/src/Plugin/Block/SubsitesBannerBlock.php                                                  
 ------ ---------------------------------------------------------------------------------------------------------------------------- 
  42     Method Drupal\localgov_subsites\Plugin\Block\SubsitesAbstractBlockBase::getSubsite() invoked with 1 parameter, 0 required.  
  44     Access to an undefined property Drupal\localgov_subsites\Plugin\Block\SubsitesBannerBlock::$entityTypeManager.              
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                        
 ------ ---------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_subsites/src/Plugin/Block/SubsitesNavigationBlock.php                  
 ------ ------------------------------------------------------------------------------------------------ 
  10     Interface Drupal\node\NodeInterface referenced with incorrect case: Drupal\Node\NodeInterface.  
  92     Variable $subsite_id might not be defined.                                                      
  95     Variable $overview_entity might not be defined.                                                 
 ------ ------------------------------------------------------------------------------------------------ 

 ------ --------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_subsites/src/Subsite.php                                      
 ------ --------------------------------------------------------------------------------------- 
  42     Access to an undefined property Drupal\localgov_subsites\Subsite::$entityTypeManager.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property   
  61     Access to an undefined property Drupal\localgov_subsites\Subsite::$entityTypeManager.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property   
 ------ --------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_subsites/tests/src/Functional/SubsitePagesTest.php                                
 ------ ----------------------------------------------------------------------------------------------------------- 
  68     Access to an undefined property Drupal\Tests\localgov_subsites\Functional\SubsitePagesTest::$nodeStorage.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                       
 ------ ----------------------------------------------------------------------------------------------------------- 
```

### PR DESCRIPTION
**Pull request by millnut**
Fix issues reported in https://github.com/localgovdrupal/localgov_subsites/issues/127

### CODE REVIEW

File: src/Plugin/Block/SubsitesBannerBlock.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ class SubsitesBannerBlock extends SubsitesAbstractBlockBase {
   public function build() {
     $build = [];
 
-    if ($this->getSubsite($this->node)) {
+    if ($this->getSubsite()) {
```
Comment (millnut) [inline src/Plugin/Block/SubsitesBannerBlock.php:42]: This function does not have parameters so this can be removed

File: tests/src/Functional/SubsitePagesTest.php [hunk 2]
```diff
@@ -36,6 +36,13 @@ class SubsitePagesTest extends BrowserTestBase {
    */
   protected $adminUser;
 
+  /**
+   * Node to hold the article.
+   *
+   * @var \Drupal\node\NodeInterface
+   */
+  protected $nodeStorage;
```
Comment (millnut) [inline tests/src/Functional/SubsitePagesTest.php]: Could use a second opinion here as it doesn't look like this is used so we could even remove this and line https://github.com/localgovdrupal/localgov_subsites/pull/128/files#diff-321651c1769e42606d07218c14d8f37ac09f160358eb1abef5b4c416126931e5R75

File: src/Plugin/Block/SubsitesBannerBlock.php (hunk 1 above)
Comment (Adnan-cds) [reply src/Plugin/Block/SubsitesBannerBlock.php:42]: Agree.

File: tests/src/Functional/SubsitePagesTest.php (hunk 2 above)
Comment (Adnan-cds) [reply tests/src/Functional/SubsitePagesTest.php]: Yes, please remove this.

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Thanks.  Feel free to remove the `$nodeStorage` declaration from SubsitePagesTest.php

**Comment by finnlewis** [comment]
@millnut leaving for you to update as Adnan suggested
